sudo: false

language: java

jdk:
  - oraclejdk8

# https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338
addons:
  apt:
    packages:
      - oracle-java8-installer

install: ./gradlew check
